### ISSUE TITLE
API 스펙문서 작성 방법

### ISSUE THREAD

**Issue by kyungmi** [ridibooks/style-guide#12]
문서에 보면 Public API의 경우에 Blueprint 스펙을 작성하라고 되어 있는데,
Protected API는 이전과 동일하게 RAML로 작성하면 되는거죠?

**Comment by namenu** [comment]
방금 @freekering 님과 얘기하다가, 현재 Jenkins로 빌드하고 있는 RAML은 버리는 것으로 결정되었습니다.
오늘 오라클에 인수된.. Apiary.io 혹은 다른 온라인 툴을 셋팅하고 전달드리겠습니다.
