### ISSUE TITLE
Java non-public 인 경우 m prefix

### ISSUE THREAD

**Issue by namenu** [ridibooks/style-guide#13]
AOSP 가이드에서는 아래와 같은 규칙이 있습니다.

- Non-public, non-static field names start with m.
- Static field names start with s.

현재 Java 코딩 스타일에서 변수명 앞의 prefix는 모두 금지하고 있는데,
그 이유가 IDE 에서 구분 가능하기 때문인 이유 외에는 없는지요?

**Comment by freekering** [comment]
@namenu 네 그 이유+올드한 느낌 때문이고 다른 이유는 없습니다.

**Comment by antiline** [comment]
스토리쪽 안드 리펙토링 하면서 코드를 보고 있습니다.

종종 변수의 스코프가 맞는지 확인하느라 코드 읽는데 딜레이가 발생합니다.
 - 물론 IDE가 색으로 표시를 해주고 있지만, 익숙하지 않아 딜레이가 발생하는것도 있습니다.

그리고 파라메터로 넘어온 변수와 맴버변수의 구분을 위해 this.로 접근하는 일관되지 않은 코드 작성이 있어 
변수 스코프 간의 차이점을 두는게 좋다고 생각됩니다.

**Comment by freekering** [comment]
http://stackoverflow.com/questions/2092098/why-do-most-fields-class-members-in-android-tutorial-start-with-m
https://google.github.io/styleguide/javaguide.html#s5.1-identifier-names

사실 링크된 AOSP의 가이드는 위 링크된 Stackoverflow 답변처럼 AOSP의 contribution 가이드이지 개별 적인 안드로이드 어플리케이션 코딩 스타일에 대한 가이드는 아닙니다. 다만 AOSP 가이드를 따르기로 한 것은 다른 안드로이드 개발 시에는 필연적으로 AOSP 코드를 레퍼런스할 일이 많다는 점과 코딩 스타일을 일일이 지정하는 것보다는 레퍼런스가 있으면 가이드를 만들기가 편하기 때문이었습니다. 그 중에서도 변수명 prefix 규칙을 예외로 둔 것은 특별히 불필요하고 번거롭다고 생각해서입니다. 다른 링크의 Google Java style guide에서는 또 사용을 안하고 있네요. 어쨌든 Java에 한해 이 규칙은 현재로서는 Google에서도 AOSP에만 적용되고 있는 것으로 보입니다.

리디북스앱에서 사용 중인 라이브러리 위주로 서치를 해보니, 대체적으로 범용 Java 라이브러리인 경우 prefix를 사용하지 않는 것으로 보이고 안드로이드용 라이브러리인 경우는 좀 갈리는데 Facebook, Google을 제외하고는 거의 사용하지 않는 것 같습니다. 이 두 곳도 Java 범용 라이브러리에는 사용하지 않고 있습니다.

**Comment by freekering** [comment]
이 Issue의 토픽이 'Java' 인 점을 고려하면 범용 Java 라이브러리들 대세에 맞게 prefix를 사용하지 않는 쪽이 맞는 것 같고, 굳이 안드로이드로 한정하더라도 특별한 이유 없이 안드로이드에만 예외를 두는 것도 바람직하지 않은 것 같습니다.

**Comment by freekering** [comment]
파라메터로 넘어온 변수와 멤버변수의 구분을 위해 this.를 사용하는 경우는 대부분 생성자와 setter에서 매우 정형화된 패턴으로 발생하기 때문에 크게 문제되지 않는다고 생각됩니다.

**Comment by namenu** [comment]
네. 상황 잘 이해했습니다.
저는 현재 가이드에서 특별히 수정을 해야할 필요성은 느끼지 못했습니다.
@antiline 님, 의견 부탁드리고 문제없다면 close 부탁드립니다.

**Comment by antiline** [comment]
그러면 맴버 변수들에 대한 접근은 this. 통해서 무조건 명시적으로 하는건 어떻게 생각하시나요?

**Comment by freekering** [comment]
뷰어팀 분들의 의견을 들어보겠습니다.

**Comment by iamstevechang** [comment]
제 개인적인 의견과 취향을 말씀드리자면, 모든 멤버 변수들에 대한 접근에 this. 를 붙히게 된다면 특정 상황에선 불필요하게 코드가 길어질 수 있고 그에따라 가독성이 떨어질 수 있다고 생각합니다. 개발자가 코드를 작성할때 local variable과 멤버 변수가 이름이 겹치는 경우에만 멤버 변수를 접근할때 this.를 붙히도록 유의하며 코드를 작성하는게 가장 최선이지 않을까 생각합니다.

**Comment by ecsca** [comment]
일단, 멤버 변수들에 대한 접근에 항상 this를 명시하도록 강제하는것은 너무 과하다고 생각되어 반대합니다. 
@freekering  님 말씀대로 일부 정형화된 패턴하에서 parameter - 멤버변수 구분을 위해 사용하는 경우 외에 단순히 scope를 파악하기위해서 this를 쓰는건 너무 과한 처사라, 오히려 가독성 / 생산성에 악영향을 줄 것 같다고 생각해요.

차라리 정 scope를 파악하기 힘들다면 prefix를 사용하는것이 더 좋은 선택이라고 생각되는데, 이 부분에 대해서는 저도 입사 초기 prefix가 없는 것에 대해 불편함이 좀 있기도 했지만, 개발하다보니 생각보다 빠르게 적응해서 (IDE의 영향도 크다고 생각되긴합니다.) '굳이 prefix를 사용하지 않는것도 괜찮다.' 정도로 정리한 상태라 prefix 사용 여부에 대해 강하게 주장하지는 못하겠네요.

**Comment by iamstevechang** [comment]
@ecsca 님 말씀대로 scope 파악하기 불편하다는 점이 반드시 개선되어야 한다면 항상 this를 쓰는 것 보다는 prefix를 사용하는 편이 더 나은 방법이라는 점에 공감합니다. 항상 this를 사용하는 것 만은 피하고싶네요..

**Comment by ecsca** [comment]
추가로 말씀드리면, 결국 'variable scope를 구분하기 힘들만큼 사용하는 변수가 많은가?' 에 대한 답에 따라 prefix가 필요한가에 대한 결정을 할 수 있을 것 같은데, 그건 순전히 취향차이인것같습니다. 

다만 제 생각을 말씀드리면 aosp같이 코드 규모가 크다면 (많은 파일이 over 1K lines, 5K 이상의 파일도 여럿 존재.) prefix가 필요할 것 같지만, 지금까지 제가 개발에 참여해온 android viewer 프로젝트는 prefix가 꼭 필요다고 생각하지 않습니다. 
결국 프로젝트 규모에 따라 적절히 선택하는게 좋지 않을까 생각합니다.

**Comment by antiline** [comment]
this 보단 prefix 가 나은데 prefix 는 위에서 쓰지 않기로 했으니 이 이슈는 여기서 종료 하겠습니다.
@ecsca 님 말씀대로 초기라 불편하지, 추후에는 익숙해질 것으로 예상합니다.
