### ISSUE TITLE
Eslint: require-jsdoc 옵션 추가

### ISSUE THREAD

**Issue by kyungmi** [ridibooks/style-guide#19]
스타일 가이드에 comment에 대한 내용이 없는데요.
javascript의 경우에 아래와 같이 jsdoc을 강제하는 건 어떻게 생각하시나요?

```json
/* ESLint Config */
{
    "require-jsdoc": ["error", {
        "require": {
            "FunctionDeclaration": true,
            "MethodDefinition": true,
            "ClassDeclaration": true,
            "ArrowFunctionExpression": true
        }
    }]
}
```

airbnb ESLint 설정에서는 `"require-jsdoc": "off"`로 설정되어 있습니다.

참고: http://eslint.org/docs/rules/valid-jsdoc

**Comment by kyungmi** [comment]
추가적으로, (linter로 강제하지 않더라도) 파일 comment 형식은 정의하는게 좋지 않을까 하는 생각도 듭니다.
코드를 읽을때마다 무슨 일을 하는 파일인지를 요약해주는 부분이 있으면 이해하기가 훨씬 수월할 것 같아요.

**Comment by namenu** [comment]
옵션을 켜봤더니 모든 React Component 의 render() 함수에 JSDoc이 붙지 않으면 에러가 발생합니다.

컴파일 타임 타입 체크를 위해서라면 TypeScript 나 Elm 등을 사용하는 것이 대안이 되겠고,
문서화를 위해서라면 조금 과한것 같습니다.

**Comment by kyungmi** [comment]
네 저도 잠시 옵션을 켜놓고 써보니 강제하는건 좀 무리가 있을것 같다는 생각이 들었습니다.
가이드라인 정도를 제공하는 것은 어떨까요?

**Comment by namenu** [comment]
@kyungmi 옵션에 대해서 고민을 좀 해봤는데요 (길었습니다 ㅎㅎ)
우리의 가이드에서는 MUST/MUST NOT 만 명시하고 SHOULD/SHOULD NOT/MAY 는 없애려고 합니다.
https://www.ietf.org/rfc/rfc2119.txt
반드시 지켜지지 않아도 되는 규칙을 포함하는 순간 너무 규모가 커지는데, 우리 규모에서 관리할 여력이 없기 때문에 그렇게 판단했고요. 추후 혼란이 커진다면 강제하는것으로 재논의를 할 수 있겠습니다.

**Comment by kyungmi** [comment]
네 충분히 이해했습니다. ㅎㅎ
사실 코멘트 같은 경우는 강제 했을 경우에 (업데이트가 되지 않아 없는 것만 못한) 부작용이 생기는 경우가 많아서 조금 조심스러운 부분이긴 합니다.
단지 요즘 함수대 함수로 포팅 작업을 하고있다 보니 함수의 기능이나 인풋 아웃풋을 쉽게 알 수 있는 코멘트가 있으면 좋지 않을까 싶어서 말씀드렸던 거였어요.

**Comment by namenu** [comment]
대신 valid-jsdoc을 넣으면 어떨까요?
JSDoc은 단순 주석이 아니라 코드라고 간주해야 하는데, 실제 함수 시그너처랑 일치하지 않으면 IDE에서 타입힌팅이 잘 되지 않을 수 있습니다. (PHPDoc 사례에서)


```js
"rules": {
    "valid-jsdoc": [
      "error",
      {
        "requireReturn": false,
        "requireParamDescription": false,
        "requireReturnDescription": false
      }
    ]
}
```

**Comment by kyungmi** [comment]
앗. `valid-jsdoc`이 있는지 몰랐네요. 추가하면 좋을 것 같습니다.
