### ISSUE TITLE
*_unicode_ci vs *_general_ci

### ISSUE THREAD

**Issue by kyungmi** [ridibooks/style-guide#27]
Mysql 가이드에 보면 Collation으로 `utf8_unicode_ci` or `utf8mb4_unicode_ci`를 쓰라고 되어 있는데, *_general_ci를 쓰지 않는 이유는 무엇인가요?
복잡한 정렬이나 검색을 사용하지 않는다면 꼭 *_unicode_ci를 사용할 필요는 없지 않을까요?

**Comment by namenu** [comment]
네, 좋은 지적이라고 생각합니다.

2011년쯤 같은 고민을 했었는데, 그 당시에도 두 collation 간의 성능 차이는 무시할만한 수준이지만 지금은 더 미미해졌습니다. 하지만 정합성 측면에서 _unicode_ci 는 맞고 _general_ci 는 틀리기 때문에 _general_ci 를 사용해야할 이유는 없다고 생각합니다.

진짜 이유: 기존 테이블이 unicode_ci 로 되어있어서 collation mismatch 를 피하기 위해 어쩔 수 없는 선택이었습니다...

**Comment by kyungmi** [comment]
성능 차이가 무시할만한 수준이라면 `_unicode_ci`를 쓰는게 낫겠군요. 참고할게요~
