### ISSUE TITLE
no-cond-assign에 대한 예외 추가 요청

### ISSUE THREAD

**Issue by kyungmi** [ridibooks/style-guide#3]
regex를 사용하면서 다음과 같은 코드를 쓰는데, `no-cond-assign`에 대한 예외 처리나 혹은 다른 방법으로 작성하기 위한 가이드가 필요하다고 느꼈습니다.

```javascript
let execResult;
while ((execResult = regex.exec(cond)) !== null) {
  //...
}
```

.eslintrc에는 다음과 같이 추가하면 될 것 같습니다.
```
"no-cond-assign": [2, "except-parens"]
```

`no-plusplus`는 말씀드리려고 했는데, 이미 추가하셨네요. ㅎㅎ

**Comment by namenu** [comment]
말씀하신 부분이 합리적으로 보여서 반영하였습니다.
해당 airbnb 규칙에 대한 특별한 설명이나 기준을 찾을 수 없었습니다.
