### ISSUE TITLE
Restful API 가이드에 응답 형태 추가 요청

### ISSUE THREAD

**Issue by kyungmi** [ridibooks/style-guide#6]
Viewer API를 재설계중입니다. 응답 형태를 아래와 같이 하려고 생각중인데 어떻게 생각하시나요? (따로 정리된 문서가 스토어 컨플루언스 페이지 밖에 없어서 그쪽을 참고했습니다.)

```javascript
// Success: result[, total_count] 필드 포함
{ result: [...], total_count: 111 }
{ result: {...} }

// Fail: code, message[, user_message는 필요하다면] 필드 포함
{ code: '...', message: '...in English...'  }
```

HTTP Status Code는 200(, 201, 204), 400, 401, 403, 404(, 409), 500, 503 사용하는 정도로 제한하면 좋을 것 같은데, 아까 의견을 들어보니 파일 I/O가 일어나야 하는 API의 경우에는 423 LOCKED나 429 TOO MANY REQUESTS 같은 코드도 사용해야 할 것 같더라고요.

에러 코드(code) 정의 방법도 생각해봐야 할 것 같습니다.
가장 일반적인 형태가 `읽을 수 있는 문자열`(예: AccountAlreadyExists, MALFORMED_ID) vs `코드 형태의 문자열 or 숫자`(예: BEA-000001, 200003) 인데,
저는 prefix가 붙는 코드 형태가 좋을 것 같습니다.

@namenu @freekering

**Comment by namenu** [comment]
우선, 항상 정확한 HTTP Response code 를 사용하는것은 강제하는것이 좋을것 같습니다.
따라서 예시에서처럼 Payload 에 200, 404 등이 포함되는것은 불필요해질 것이고요,
그러면 논의를 "도메인 특화된 에러코드 정의 규약을 정할 것인가? 정한다면 어떻게 정의할 것인가?" 이렇게 좁힐 수 있을것 같아요.

각 팀 의견을 수렴해야 해서 @genesos @earus @iamchanu 를 소환했습니다.

**Comment by kyungmi** [comment]
@namenu 제가 오해를 불러일으키게끔 작성했네요 ㅎㅎ payload 자체에 statusCode를 포함시키는 것이 아니라 HTTP Header의 statusCode를 저 정도로 제한하자는 뜻이었고요.
도메인 특화된 에러코드 정의 규약을 정하는 쪽으로 초점을 맞추면 될 듯 합니다.

예를 들면 전에 작성했던 simple-notifier에서는 401 에러의 의미를 세분화 하는 방식으로 에러코드를 정했는데요.
토큰이 만료되서 401 에러가 난 경우와 사용자 이름이나 패스워드를 잘못 입력했을 경우 등을 구별했습니다.
그리고 에러코드와 에러 메세지는 1:1로 매칭되고요.

**Comment by namenu** [comment]
@kyungmi 앗, 그렇군요. 여튼 HTTP Status Code 관련 내용이 보강될 필요는 있어서 #8로 생성은 해두었습니다ㅋ

음.. 도메인 특화 에러를,
 - 문자열로만 작성하면 CS 응대시 정확한 파악이 어렵고
 - 코드로만 작성하면 dereferencing 비용이 있고
 - 둘 다로 작성하면 파싱이 불편하고
대충 이런 것들이 생각납니다.

**Comment by kyungmi** [comment]
@namenu 에러코드는 사용자에게 직접 노출되는 값은 아니니까 개발자가 보기에 대충 어떤 종류의 에러겠구나를 판단할 수 있는 정도면 괜찮을 것 같습니다. 자세한 내용은 message 필드가 보충을 해줄 것 같고요.

dereferencing 비용이 있다는 부분이 잘 이해가 안되는데 설명 부탁드릴게요.

**Comment by namenu** [comment]
예를 들어서 현재 K사의 DRM 에러코드는 숫자로 되어 DB에 기록되고 있는데, 매번 숫자의 의미를 몰라서 소스코드를 참고하고 있습니다. 생각보다 잘 외워지지가 않더라고요.

**Comment by namenu** [comment]
저희가 하는 고민을 네이버 API는 이렇게 해결했네요.
https://developers.naver.com/docs/labs/tts

**Comment by kyungmi** [comment]
@namenu 코드 형태의 에러코드를 사용하게 된다면 네이버 API처럼 에러 메세지가 상세한 편이 좋을것 같네요.

**Comment by kyungmi** [comment]
대략적으로 에러코드를 정의해 봤습니다. (일반적인 코드와 뷰어 한정적인 코드가 섞여 있습니다.)
https://ridicorp.atlassian.net/wiki/pages/viewpage.action?pageId=104153413

에러 코드는 6자리 숫자로 했고요.
맨 앞의 세 자리는 HTTP Status Code를 그대로 쓰고, 나머지 3자리는 각각 대분류, 소분류, 상세 정보로 구조화했습니다.

여기다 링크를 걸어도 되는지 모르겠네요.
의견 주시면 감사하겠습니다.
