### ISSUE TITLE
eslint-config-ridibooks 

### ISSUE THREAD

**Issue by kyungmi** [ridibooks/style-guide#7]
airbnb처럼 저희도 `eslint-config-ridibooks`라는 npm package를 등록해서
```
extends: 'ridibooks'
```
로 설정하면 참 좋을 것 같습니다! :)

바쁘시면 제가 작업해도 될 것 같아요.

참고: http://eslint.org/docs/user-guide/configuring#using-a-shareable-configuration-package

**Comment by namenu** [comment]
와.. 사실 생각만하고 시작은 못했었는데, 만들어주시면 모두가 행복할것 같습니다 👍

**Comment by kyungmi** [comment]
대신 npm 배포를 (ㅋㅋ) 부탁드립니다. 작업한 다음에 다시 이슈 생성할게요.

**Comment by kyungmi** [comment]
@namenu 
https://github.com/ridibooks/eslint-config-ridibooks 에 repository 생성했습니다.
npm 배포 부탁드릴게요. 잘 될진 모르겠네요.

**Comment by kyungmi** [comment]
생각해보니까 이 repository 안에 서브 디렉터리로 만드는게 더 낫지 않을까 하는 생각이 드네요. ㅋ

**Comment by namenu** [comment]
@kyungmi 네, airbnb를 보니까 package.json 이 루트에 없어도 되는것 같더라고요. 물론 방법은 잘 모르겠습니다 ㅎㅎ

**Comment by kyungmi** [comment]
package.json 파일이 존재하는 npm root라면 어떤 디렉터리 하에 있던지 상관 없이 배포가 가능한 걸로 알고 있는데 저도 시도는 해본적이 없어서 모르겠네요. 
감사합니다~

**Comment by kyungmi** [comment]
@namenu 재배포 부탁드립니다 ㅎㅎ

**Comment by namenu** [comment]
npmjs.com 자체에는 버전 bump 기능이 없네요.
로컬에서 ```npm version minor``` 를 수행하신 뒤에 push 하면 알아서 올라가는듯 합니다.

**Comment by kyungmi** [comment]
아 버전업을 안 했네요. 작업 완료했습니다.
알아서 올라가지는 않는 것 같군요 ㅎㅎ

**Comment by namenu** [comment]
@kyungmi 자동 배포 설정하였고, 1.1.0 배포되었습니다. 이제 다른 프로젝트에 하나씩 적용해봐야곘군요.
