### ISSUE TITLE
.swiftlint.yml 추가

### ISSUE THREAD

**Issue by namenu** [ridibooks/style-guide#9]
@DaVinAhn 언어별로 lint 설정을 공유해서 사용하고 있는데, Swift 버전도 등록 가능한 상태일까요?

**Comment by DaVinAhn** [comment]
@namenu 
넴넴, 가능한 상태에요

**Comment by DaVinAhn** [comment]
@namenu 
어디에 올리면 될까요?

**Comment by namenu** [comment]
Swift 라는 폴더를 만들고 거기다 올리면 좋을것 같습니다.
Pull Request 주세요!
